import { ScrollView, Text, View, StyleSheet, TouchableOpacity } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useRouter } from "expo-router";
import { Ionicons } from "@expo/vector-icons";
import { colors, spacing } from "../src/theme";

export default function TermsScreen() {
  const router = useRouter();
  return (
    <SafeAreaView style={styles.container} edges={["top"]}>
      <View style={styles.topBar}>
        <TouchableOpacity onPress={() => router.back()} testID="terms-back-btn">
          <Ionicons name="chevron-back" size={26} color={colors.textPrimary} />
        </TouchableOpacity>
        <Text style={styles.topTitle}>TERMS OF SERVICE</Text>
        <View style={{ width: 26 }} />
      </View>
      <ScrollView contentContainerStyle={styles.content}>
        <Text style={styles.lastUpdated}>Last updated: June 2025</Text>

        <Section title="1. Acceptance of Terms">
          By creating an account or using SurfCoach23 (the "App"), you agree to
          these Terms of Service. If you do not agree, please do not use the App.
        </Section>

        <Section title="2. The Service">
          SurfCoach23 provides AI-powered surf-technique video analysis,
          subscription tiers, and a coach directory. Analyses are produced by
          third-party AI models (Google Gemini, Anthropic Claude) and are for
          informational purposes only — not professional coaching, medical, or
          safety advice.
        </Section>

        <Section title="3. Accounts">
          You must provide accurate sign-in information and you are responsible
          for activity on your account. You must be at least 13 years old to
          use the App (16 in the EU). Surfing carries physical risk; you are
          solely responsible for your own safety in the water.
        </Section>

        <Section title="4. Subscriptions & Payments">
          Paid plans (LEARN, Advanced, PRO) are billed monthly through
          LemonSqueezy in Saudi Riyal (SAR). Subscriptions auto-renew until
          cancelled. You can cancel renewal anytime from the Manage Plan screen
          — your access stays active until the current period ends.
          {"\n\n"}
          Free plan members receive one (1) AI analysis on a lifetime basis.
          Daily limits on paid plans reset at 00:00 UTC.
        </Section>

        <Section title="5. Refunds">
          Subscription fees are non-refundable except where required by law.
          You may cancel at any time to prevent future charges. If you believe
          you were charged in error, contact support within 7 days.
        </Section>

        <Section title="6. User Content">
          You retain ownership of videos you upload. By uploading, you grant
          SurfCoach23 a limited licence to process the video through our AI
          pipeline and store the result associated with your account. Videos
          shared with a coach are visible to that coach only. We do not sell
          your content.
        </Section>

        <Section title="7. Acceptable Use">
          Do not upload illegal, harmful, or third-party-copyrighted videos.
          Do not attempt to disrupt the service, reverse-engineer the AI, or
          impersonate other users.
        </Section>

        <Section title="8. AI Output Disclaimer">
          AI feedback is generated by machine-learning models and may contain
          inaccuracies. Use it as one of many references; always consult a
          qualified human coach for safety-critical decisions.
        </Section>

        <Section title="9. Termination">
          We may suspend or terminate accounts that violate these terms.
          You may delete your account anytime from Profile → Settings.
        </Section>

        <Section title="10. Limitation of Liability">
          To the maximum extent permitted by law, SurfCoach23 is provided
          "as is" without warranty. We are not liable for indirect, incidental,
          or consequential damages.
        </Section>

        <Section title="11. Changes">
          We may update these Terms; we will notify you in-app of material
          changes. Continued use after changes means you accept the new Terms.
        </Section>

        <Section title="12. Contact">
          Questions? Email <Text style={styles.link}>support@surfcoach23.app</Text>.
        </Section>

        <View style={{ height: spacing.xxl }} />
      </ScrollView>
    </SafeAreaView>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <View style={styles.section}>
      <Text style={styles.sectionTitle}>{title}</Text>
      <Text style={styles.body}>{children}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  topTitle: {
    color: colors.textPrimary,
    letterSpacing: 2,
    fontSize: 12,
    fontWeight: "800",
  },
  content: { padding: spacing.lg },
  lastUpdated: {
    color: colors.textMuted,
    fontSize: 11,
    marginBottom: spacing.lg,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  section: { marginBottom: spacing.lg },
  sectionTitle: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: "800",
    letterSpacing: 1,
    marginBottom: 8,
    textTransform: "uppercase",
  },
  body: { color: colors.textPrimary, fontSize: 14, lineHeight: 22 },
  link: { color: colors.primary, fontWeight: "700" },
});
